# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analiz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 527)
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(190, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(17)
        self.label1.setFont(font)
        self.label1.setStyleSheet("label1")
        self.label1.setObjectName("label1")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 110, 171, 51))
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(30, 80, 681, 111))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(30, 200, 681, 111))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(30, 320, 681, 161))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 240, 171, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 360, 171, 81))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(530, 90, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("introver")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_sort1 = QtWidgets.QComboBox(Form)
        self.comboBox_sort1.setGeometry(QtCore.QRect(530, 120, 121, 21))
        self.comboBox_sort1.setObjectName("comboBox_sort1")
        self.comboBox_sort1.addItem("")
        self.comboBox_sort1.addItem("")
        self.view1 = QtWidgets.QPushButton(Form)
        self.view1.setGeometry(QtCore.QRect(530, 160, 121, 20))
        self.view1.setObjectName("view1")
        self.comboBox_group = QtWidgets.QComboBox(Form)
        self.comboBox_group.setGeometry(QtCore.QRect(530, 220, 121, 22))
        self.comboBox_group.setObjectName("comboBox_group")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.view2 = QtWidgets.QPushButton(Form)
        self.view2.setGeometry(QtCore.QRect(530, 280, 121, 20))
        self.view2.setObjectName("view2")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(270, 330, 121, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(270, 360, 121, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(270, 390, 121, 21))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(270, 420, 121, 21))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setGeometry(QtCore.QRect(270, 450, 121, 21))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(530, 350, 121, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.view3 = QtWidgets.QPushButton(Form)
        self.view3.setGeometry(QtCore.QRect(530, 450, 121, 20))
        self.view3.setObjectName("view3")
        self.graphicsView_3.raise_()
        self.graphicsView_2.raise_()
        self.graphicsView.raise_()
        self.label1.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.comboBox_sort1.raise_()
        self.view1.raise_()
        self.comboBox_group.raise_()
        self.view2.raise_()
        self.comboBox_3.raise_()
        self.comboBox_4.raise_()
        self.comboBox_5.raise_()
        self.comboBox_6.raise_()
        self.comboBox_7.raise_()
        self.comboBox_2.raise_()
        self.view3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label1.setText(_translate("Form", "  Анализ тестов BigFive"))
        self.label.setText(_translate("Form", "Упорядочить по параметру "))
        self.label_2.setText(_translate("Form", "Статистика по группам"))
        self.label_3.setText(_translate("Form", "Упорядочить по параметру "))
        self.comboBox.setItemText(0, _translate("Form", "Интроверсия"))
        self.comboBox.setItemText(1, _translate("Form", "Пассивность"))
        self.comboBox.setItemText(2, _translate("Form", "Подчиненность"))
        self.comboBox.setItemText(3, _translate("Form", "Замкнутость"))
        self.comboBox.setItemText(4, _translate("Form", "избегание впечатлений"))
        self.comboBox.setItemText(5, _translate("Form", "избегание внимания"))
        self.comboBox.setItemText(6, _translate("Form", "обособленность"))
        self.comboBox.setItemText(7, _translate("Form", "равнодушие"))
        self.comboBox.setItemText(8, _translate("Form", "соперничество"))
        self.comboBox.setItemText(9, _translate("Form", "подозрительность"))
        self.comboBox.setItemText(10, _translate("Form", "непонимание"))
        self.comboBox.setItemText(11, _translate("Form", "самоуважение"))
        self.comboBox.setItemText(12, _translate("Form", "импульсивность"))
        self.comboBox.setItemText(13, _translate("Form", "неаккуратность"))
        self.comboBox.setItemText(14, _translate("Form", "отсутствие настойчивости"))
        self.comboBox.setItemText(15, _translate("Form", "безответственность"))
        self.comboBox.setItemText(16, _translate("Form", "импульсивность"))
        self.comboBox.setItemText(17, _translate("Form", "беспечность"))
        self.comboBox.setItemText(18, _translate("Form", "эмоц. устойчивость"))
        self.comboBox.setItemText(19, _translate("Form", "беззаботность"))
        self.comboBox.setItemText(20, _translate("Form", "расслабленность"))
        self.comboBox.setItemText(21, _translate("Form", "эмоц. комфортность"))
        self.comboBox.setItemText(22, _translate("Form", "самодостаточность"))
        self.comboBox.setItemText(23, _translate("Form", "эмоц. стабильность"))
        self.comboBox.setItemText(24, _translate("Form", "практичность"))
        self.comboBox.setItemText(25, _translate("Form", "консерватизм"))
        self.comboBox.setItemText(26, _translate("Form", "реалистичность"))
        self.comboBox.setItemText(27, _translate("Form", "отсутствие артистичности    "))
        self.comboBox.setItemText(28, _translate("Form", "нечувствительность"))
        self.comboBox.setItemText(29, _translate("Form", "ригидность"))
        self.comboBox_sort1.setItemText(0, _translate("Form", "Возрастание"))
        self.comboBox_sort1.setItemText(1, _translate("Form", "Убывание"))
        self.view1.setText(_translate("Form", "Показать"))
        self.comboBox_group.setItemText(0, _translate("Form", "5381"))
        self.comboBox_group.setItemText(1, _translate("Form", "5383"))
        self.view2.setText(_translate("Form", "Показать"))
        self.comboBox_3.setItemText(0, _translate("Form", "интроверсия"))
        self.comboBox_3.setItemText(1, _translate("Form", "обособленность"))
        self.comboBox_3.setItemText(2, _translate("Form", "импульсивность"))
        self.comboBox_3.setItemText(3, _translate("Form", "эмоц. устойчивость"))
        self.comboBox_3.setItemText(4, _translate("Form", "практичность"))
        self.comboBox_4.setItemText(0, _translate("Form", "интроверсия"))
        self.comboBox_4.setItemText(1, _translate("Form", "обособленность"))
        self.comboBox_4.setItemText(2, _translate("Form", "импульсивность"))
        self.comboBox_4.setItemText(3, _translate("Form", "эмоц. устойчивость"))
        self.comboBox_4.setItemText(4, _translate("Form", "практичность"))
        self.comboBox_5.setItemText(0, _translate("Form", "интроверсия"))
        self.comboBox_5.setItemText(1, _translate("Form", "обособленность"))
        self.comboBox_5.setItemText(2, _translate("Form", "импульсивность"))
        self.comboBox_5.setItemText(3, _translate("Form", "эмоц. устойчивость"))
        self.comboBox_5.setItemText(4, _translate("Form", "практичность"))
        self.comboBox_6.setItemText(0, _translate("Form", "интроверсия"))
        self.comboBox_6.setItemText(1, _translate("Form", "обособленность"))
        self.comboBox_6.setItemText(2, _translate("Form", "импульсивность"))
        self.comboBox_6.setItemText(3, _translate("Form", "эмоц. устойчивость"))
        self.comboBox_6.setItemText(4, _translate("Form", "практичность"))
        self.comboBox_7.setItemText(0, _translate("Form", "интроверсия"))
        self.comboBox_7.setItemText(1, _translate("Form", "обособленность"))
        self.comboBox_7.setItemText(2, _translate("Form", "импульсивность"))
        self.comboBox_7.setItemText(3, _translate("Form", "эмоц. устойчивость"))
        self.comboBox_7.setItemText(4, _translate("Form", "практичность"))
        self.comboBox_2.setItemText(0, _translate("Form", "Среднее"))
        self.comboBox_2.setItemText(1, _translate("Form", "Максимальное"))
        self.comboBox_2.setItemText(2, _translate("Form", "Минимальное"))
        self.view3.setText(_translate("Form", "Показать"))

